#lang sicp
(define (double x) (+ x x))
(define (halve x) (/ x 2))
(define (even? x)
  (= (remainder x 2) 0))
(define (f1 a b)
  (cond ((= b 0) 0)
        ((even? b) (double (f1 a (halve b))))
        (else (+ a (f1 a (- b 1))))))
(define (f2 a b)
  (define (iter x y s)
    (cond ((= y 0) s)
          ((even? y) (iter (double x) (halve y) s))
          (else (iter x (- y 1) (+ s x)))))
  (iter a b 0))