#lang sicp
(define (and? exp) (tagged-list? exp 'and))
(define (or? exp) (tagged-list? exp 'or))
(define (expression exp) (cdr exp))
(define (first exp) (car exp))
(define (rest exp) (cdr exp))
(define (last? exp) (eq? nil (rest exp)))
(define (eval-and exp env)
  (cond ((null? exp) 'true)
        ((last? exp) (eval (first exp) env))
        ((true? (eval (first exp) env)) (eval-and (rest exp) env))
        (else 'false)))
(define (eval-or exp env)
  (cond ((null? exp) 'false)
        ((true? (eval (first exp) env)) 'true)
        (else (eval-or (rest exp) env))))
(eval-and (expression exp) env)
(eval-or (expression exp) env)

