#lang sicp
(define (front-ptr queue) (car queue))
(define (rear-ptr queue) (cdr queue))
(define (set-front-ptr! queue item) (set-car! queue item))
(define (set-rear-ptr! queue item) (set-cdr! queue item))

(define (empty-queue? queue) (eq? (front-ptr queue) nil))
(define (make-queue) (cons nil nil))
(define (front-queue queue)
  (if (empty-queue? queue)
      (error "empty queue")
      (car (front-ptr queue))))
(define (insert-queue! queue item)
 (let ((newpair (cons item nil)))
   (if (empty-queue? queue)
       (begin (set-front-ptr! queue newpair)
              (set-rear-ptr! queue newpair)
              (print-queue queue))
      (begin  (set-cdr! (rear-ptr queue) newpair)
              (set-rear-ptr! queue newpair)
              (print-queue queue)))))
(define (delete-queue! queue)
  (if (empty-queue? queue)
      (error "empty queue")
      (begin (set-front-ptr! queue (cdr (front-ptr queue)))
             (print-queue queue))))
(define (print-queue queue)
  (display "(")
  (define (iter ptr)
    (if (null? ptr)
        (display ")")
        (begin (display (car ptr))
               (iter (cdr ptr)))))
  (iter (front-ptr queue))
  (newline))
;;test
(define q (make-queue))
(insert-queue! q 'a)
(insert-queue! q 'b)
(insert-queue! q 'c)
(delete-queue! q)
